In [ ]:
'''
How Bagging work?
It is an ensemble method in which the dataset is first divided into multiple subsets through resampling.
Then, each subset is used to train a model, and the final predictions are made through voting or averaging the component models.


In [ ]:
'''
Random Forest: 
    - Random forest is a tree-based algorithm which involves building several trees (decision trees), then combining their 
      output to improve generalization ability of the model

In [2]:
import warnings
warnings.filterwarnings('ignore')

### RandomForestClassifier using SKLearn

In [4]:
import numpy as np
import pandas as pd

data = pd.read_csv("diabetes.csv")
array = data.values
X = array[:,0:8]
Y = array[:,8]

from sklearn.model_selection import KFold
kfold = KFold(n_splits=10,random_state=7)

num_trees = 100
max_features = 3
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=num_trees,max_features=max_features)

from sklearn.model_selection import cross_val_score
results = cross_val_score(model,X,Y,cv=kfold)
print(results.mean())

0.7668660287081339


### RandomForestClassifier with PCA

In [5]:
# PCA for 4D to 2D for Iris DataSer
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier

names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
dataset = load_iris()

X = dataset.data
y = dataset.target

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Scaling the data
sc = StandardScaler()
X_train = sc.fit_transform(X_train)  
X_test = sc.transform(X_test)

# Applying PCA
pca = PCA(n_components=1)
X_train = pca.fit_transform(X_train)  
X_test = pca.transform(X_test)

classifier = RandomForestClassifier(max_depth=2, random_state=0)  
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test) 

from sklearn.metrics import confusion_matrix  
from sklearn.metrics import accuracy_score

cm = confusion_matrix(y_test, y_pred)  
print(cm)  
print('Accuracy',accuracy_score(y_test, y_pred))  

[[11  0  0]
 [ 0 12  1]
 [ 0  1  5]]
Accuracy 0.9333333333333333
