In [4]:
import numpy as np
import pandas as pd

data1 = pd.DataFrame({"TV":[230.1,44.5,17.2,151.5],"Radio":[37.8,39.3,45.9,41.3],
                      "News":[69.1,23.1,34.7,13.2],"Sales" : [22.1,10.4,18.3,18.5]})

print(data1)

X = data1.iloc[:,0:3] # read first two columns into X
y = data1.iloc[:,3] # read the third column into y

print("Input Data = X")
print(X.head())
print("Shape of input X", X.shape,"\n")

print("Target = y",)
print(y.head())
print("Shape of input y", y.shape,"\n")

# no. of training samples
m = len(y) 
print("No of training samples :",m,"\n")

# Normalization
print("Normalize the Input data X")
X = (X - np.mean(X))/np.std(X)
print(X.head(),"\n")

# 
ones = np.ones((m,1))
X = np.hstack((ones, X))
print(X[0:5])
print("Shape of X",X.shape,"\n")

y = y[:,np.newaxis]
print(y[0:5])
print("Shape of y",y.shape,"\n")

alpha = 0.01
print("alpha :",alpha)
num_iters = 400
print("num_iters :",num_iters,"\n")
theta = np.zeros((4,1))
print("theta :")
print(theta)
print("Shape of theta",theta.shape,"\n")
iteration = 1000
print("**********************************************************************************")

plot_loss = list()
plot_iteartion = list()

for i in range(iteration):
    plot_iteartion.append(i)
    print("Iteration = ",i)
    print("Step 1: Calculate the y_prediction","\n")
    
    y_predicted = np.dot(X, theta) 
    print("y_predicted = np.dot(X, theta)")
    print(y_predicted[0:5],"\n")
    
    error = y_predicted - y
    print("error = y_predicted - y")
    print(error[0:5],"\n")
    
    sq_error =error**2
    print("sq_error = error **2")
    print(sq_error[0:5],"\n")
    
    print("m = ",m)
    cost = sq_error.sum() / (2*m)
    print("cost = sq_error.sum() / (2*m)")
    print("cost = ",cost,"\n")
    plot_loss.append(plot_loss)
    
    print("Finding optimal parameters using Gradient Descent")
    m = len(y)
    temp = y_predicted - y
    temp = np.dot(X.T, temp)
    theta = theta - (alpha/m) * temp
    print("theta values :")
    print(theta,"\n")
    
    print("**********************************************************************************")

      TV  Radio  News  Sales
0  230.1   37.8  69.1   22.1
1   44.5   39.3  23.1   10.4
2   17.2   45.9  34.7   18.3
3  151.5   41.3  13.2   18.5
Input Data = X
      TV  Radio  News
0  230.1   37.8  69.1
1   44.5   39.3  23.1
2   17.2   45.9  34.7
3  151.5   41.3  13.2
Shape of input X (4, 3) 

Target = y
0    22.1
1    10.4
2    18.3
3    18.5
Name: Sales, dtype: float64
Shape of input y (4,) 

No of training samples : 4 

Normalize the Input data X
         TV     Radio      News
0  1.399713 -1.073807  1.615424
1 -0.778336 -0.581987 -0.565339
2 -1.098706  1.582020 -0.015408
3  0.477328  0.073773 -1.034678 

[[ 1.          1.39971314 -1.07380656  1.6154245 ]
 [ 1.         -0.77833556 -0.58198676 -0.56533931]
 [ 1.         -1.09870587  1.58202036 -0.01540757]
 [ 1.          0.47732829  0.07377297 -1.03467761]]
Shape of X (4, 4) 

[[22.1]
 [10.4]
 [18.3]
 [18.5]]
Shape of y (4, 1) 

alpha : 0.01
num_iters : 400 

theta :
[[0.]
 [0.]
 [0.]
 [0.]]
Shape of theta (4, 1) 

*****************

c:\users\insakum46\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:35: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.



[[10.51686005]
 [ 5.95235872]
 [ 6.93804873]
 [ 7.2048891 ]] 

error = y_predicted - y
[[-11.58313995]
 [ -4.44764128]
 [-11.36195127]
 [-11.2951109 ]] 

sq_error = error **2
[[134.16913104]
 [ 19.78151294]
 [129.09393676]
 [127.57953028]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  51.32801387714106 

Finding optimal parameters using Gradient Descent
theta values :
[[7.74975876]
 [1.19062756]
 [0.38433023]
 [1.01344316]] 

**********************************************************************************
Iteration =  59
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[10.64074037]
 [ 6.02643662]
 [ 7.03401283]
 [ 7.29784521]] 

error = y_predicted - y
[[-11.45925963]
 [ -4.37356338]
 [-11.26598717]
 [-11.20215479]] 

sq_error = error **2
[[131.31463127]
 [ 19.12805662]
 [126.92246697]
 [125.48827188]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  50.35667834215244 

Finding optimal parameters using Gradient Descent
theta values :
[[7.84551117]
 [1.20463925]
 

[[35.90406246]
 [ 1.16631899]
 [43.71156818]
 [47.00687063]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  15.973602533036223 

Finding optimal parameters using Gradient Descent
theta values :
[[12.24145135]
 [ 1.8847572 ]
 [ 1.00975645]
 [ 1.46932943]] 

**********************************************************************************
Iteration =  122
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[16.16887843]
 [ 9.35614322]
 [11.74547401]
 [11.69530975]] 

error = y_predicted - y
[[-5.93112157]
 [-1.04385678]
 [-6.55452599]
 [-6.80469025]] 

sq_error = error **2
[[35.17820313]
 [ 1.08963698]
 [42.96181099]
 [46.30380943]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  15.691682566401742 

Finding optimal parameters using Gradient Descent
theta values :
[[12.29228684]
 [ 1.89359713]
 [ 1.01949397]
 [ 1.47395317]] 

**********************************************************************************
Iteration =  123
Step 1: Calculate the y_prediction 

y_predicte


Finding optimal parameters using Gradient Descent
theta values :
[[14.48702692]
 [ 2.33556786]
 [ 1.53572493]
 [ 1.65992873]] 

**********************************************************************************
Iteration =  180
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[18.78856996]
 [10.83697686]
 [14.32489744]
 [13.99766343]] 

error = y_predicted - y
[[-3.31143004]
 [ 0.43697686]
 [-3.97510256]
 [-4.50233657]] 

sq_error = error **2
[[10.9655689 ]
 [ 0.19094878]
 [15.80144033]
 [20.27103456]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  5.90362407078333 

Finding optimal parameters using Gradient Descent
theta values :
[[14.51540666]
 [ 2.34245983]
 [ 1.54402324]
 [ 1.66212046]] 

**********************************************************************************
Iteration =  181
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[18.82122628]
 [10.85392374]
 [14.35879924]
 [14.02767736]] 

error = y_predicted - y
[[-3.27877372]
 [ 0.45

Finding optimal parameters using Gradient Descent
theta values :
[[16.04211229]
 [ 2.81853853]
 [ 2.10989116]
 [ 1.7638715 ]] 

**********************************************************************************
Iteration =  259
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[20.57104395]
 [11.62322889]
 [16.25608127]
 [15.71809506]] 

error = y_predicted - y
[[-1.52895605]
 [ 1.22322889]
 [-2.04391873]
 [-2.78190494]] 

sq_error = error **2
[[2.33770659]
 [1.49628892]
 [4.17760378]
 [7.73899512]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  1.968824302474539 

Finding optimal parameters using Gradient Descent
theta values :
[[16.05494117]
 [ 2.82397453]
 [ 2.11616329]
 [ 1.76450047]] 

**********************************************************************************
Iteration =  260
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[20.58576266]
 [11.62782087]
 [16.27285052]
 [15.73333063]] 

error = y_predicted - y
[[-1.51423734]
 [ 1.227820

Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[21.1459338 ]
 [11.7534535 ]
 [16.92580085]
 [16.33883267]] 

error = y_predicted - y
[[-0.9540662 ]
 [ 1.3534535 ]
 [-1.37419915]
 [-2.16116733]] 

sq_error = error **2
[[0.91024231]
 [1.83183637]
 [1.8884233 ]
 [4.67064422]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  1.1626432750498763 

Finding optimal parameters using Gradient Descent
theta values :
[[16.54884515]
 [ 3.0733892 ]
 [ 2.39696061]
 [ 1.78169449]] 

**********************************************************************************
Iteration =  309
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[21.15502928]
 [11.75445576]
 [16.9366833 ]
 [16.34921227]] 

error = y_predicted - y
[[-0.94497072]
 [ 1.35445576]
 [-1.3633167 ]
 [-2.15078773]] 

sq_error = error **2
[[0.89296967]
 [1.83455039]
 [1.85863241]
 [4.62588784]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  1.151505038816649 

Finding optimal parameters using Gradient Des

Finding optimal parameters using Gradient Descent
theta values :
[[16.9845649 ]
 [ 3.42597322]
 [ 2.76834407]
 [ 1.77039384]] 

**********************************************************************************
Iteration =  391
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[21.66721616]
 [11.70599527]
 [17.57272723]
 [16.99232094]] 

error = y_predicted - y
[[-0.43278384]
 [ 1.30599527]
 [-0.72727277]
 [-1.50767906]] 

sq_error = error **2
[[0.18730185]
 [1.70562365]
 [0.52892568]
 [2.27309616]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.5868684181646812 

Finding optimal parameters using Gradient Descent
theta values :
[[16.98796925]
 [ 3.4298304 ]
 [ 2.7722369 ]
 [ 1.77005957]] 

**********************************************************************************
Iteration =  392
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[21.67129933]
 [11.70432084]
 [17.57805736]
 [16.99819948]] 

error = y_predicted - y
[[-0.42870067]
 [ 1.30432

 [ 1.7434691 ]] 

**********************************************************************************
Iteration =  455
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[21.86381782]
 [11.57514237]
 [17.8383684 ]
 [17.30694543]] 

error = y_predicted - y
[[-0.23618218]
 [ 1.17514237]
 [-0.4616316 ]
 [-1.19305457]] 

sq_error = error **2
[[0.05578202]
 [1.38095959]
 [0.21310373]
 [1.4233792 ]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.38415306688277007 

Finding optimal parameters using Gradient Descent
theta values :
[[17.14785782]
 [ 3.65707787]
 [ 2.99526005]
 [ 1.74297998]] 

**********************************************************************************
Iteration =  456
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[21.86604042]
 [11.57284726]
 [17.84151219]
 [17.31103142]] 

error = y_predicted - y
[[-0.23395958]
 [ 1.17284726]
 [-0.45848781]
 [-1.18896858]] 

sq_error = error **2
[[0.05473709]
 [1.3755707 ]
 [0.21021107]
 [1.4136

cost =  0.267961020428342 

Finding optimal parameters using Gradient Descent
theta values :
[[17.22807548]
 [ 3.83840063]
 [ 3.16462859]
 [ 1.71156115]] 

**********************************************************************************
Iteration =  516
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[21.96743413]
 [11.43112701]
 [17.99093803]
 [17.52280274]] 

error = y_predicted - y
[[-0.13256587]
 [ 1.03112701]
 [-0.30906197]
 [-0.97719726]] 

sq_error = error **2
[[0.01757371]
 [1.06322292]
 [0.0955193 ]
 [0.95491448]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.26640380061841606 

Finding optimal parameters using Gradient Descent
theta values :
[[17.22904473]
 [ 3.84118812]
 [ 3.16717555]
 [ 1.71101425]] 

**********************************************************************************
Iteration =  517
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[21.96868663]
 [11.42875355]
 [17.99288243]
 [17.52585629]] 

error = y_predicted 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.16697387012904005 

Finding optimal parameters using Gradient Descent
theta values :
[[17.28291234]
 [ 4.04649424]
 [ 3.3502886 ]
 [ 1.66572866]] 

**********************************************************************************
Iteration =  599
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[22.04014048]
 [11.24185646]
 [18.1115653 ]
 [17.73808711]] 

error = y_predicted - y
[[-0.05985952]
 [ 0.84185646]
 [-0.1884347 ]
 [-0.76191289]] 

sq_error = error **2
[[0.00358316]
 [0.7087223 ]
 [0.03550764]
 [0.58051125]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.1660405440622013 

Finding optimal parameters using Gradient Descent
theta values :
[[17.28333321]
 [ 4.04873344]
 [ 3.35223857]
 [ 1.66518214]] 

**********************************************************************************
Iteration =  600
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[22.04071886]
 [11.23970859]
 [18.11261926]


error = y_predicted - y
[[-0.02701675]
 [ 0.6827335 ]
 [-0.12334802]
 [-0.60770956]] 

sq_error = error **2
[[0.0007299 ]
 [0.46612504]
 [0.01521473]
 [0.36931091]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.10642257306646025 

Finding optimal parameters using Gradient Descent
theta values :
[[17.30635315]
 [ 4.20987618]
 [ 3.4900536 ]
 [ 1.62305919]] 

**********************************************************************************
Iteration =  680
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[22.07325925]
 [11.08091264]
 [18.17726593]
 [17.89397476]] 

error = y_predicted - y
[[-0.02674075]
 [ 0.68091264]
 [-0.12273407]
 [-0.60602524]] 

sq_error = error **2
[[0.00071507]
 [0.46364202]
 [0.01506365]
 [0.36726659]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.10583591662285143 

Finding optimal parameters using Gradient Descent
theta values :
[[17.30653961]
 [ 4.21168076]
 [ 3.49156971]
 [ 1.62255722]] 

*********************************************

Iteration =  758
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[22.08852072]
 [10.95154672]
 [18.2150687 ]
 [18.01080652]] 

error = y_predicted - y
[[-0.01147928]
 [ 0.55154672]
 [-0.0849313 ]
 [-0.48919348]] 

sq_error = error **2
[[1.31773955e-04]
 [3.04203789e-01]
 [7.21332644e-03]
 [2.39310258e-01]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.06885739335311342 

Finding optimal parameters using Gradient Descent
theta values :
[[17.31657081]
 [ 4.33852986]
 [ 3.59671495]
 [ 1.58568937]] 

**********************************************************************************
Iteration =  759
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[22.08865338]
 [10.9500457 ]
 [18.21544724]
 [18.01213691]] 

error = y_predicted - y
[[-0.01134662]
 [ 0.5500457 ]
 [-0.08455276]
 [-0.48786309]] 

sq_error = error **2
[[1.28745792e-04]
 [3.02550276e-01]
 [7.14916943e-03]
 [2.38010395e-01]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.0684798233153

 [-0.40132836]] 

sq_error = error **2
[[1.96955573e-05]
 [2.03962677e-01]
 [3.86987029e-03]
 [1.61064456e-01]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.046114587394916896 

Finding optimal parameters using Gradient Descent
theta values :
[[17.3209528 ]
 [ 4.43541002]
 [ 3.67521802]
 [ 1.55553377]] 

**********************************************************************************
Iteration =  832
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[22.0956286 ]
 [10.85038281]
 [18.23804451]
 [18.09975526]] 

error = y_predicted - y
[[-0.0043714 ]
 [ 0.45038281]
 [-0.06195549]
 [-0.40024474]] 

sq_error = error **2
[[1.91091210e-05]
 [2.02844680e-01]
 [3.83848290e-03]
 [1.60195855e-01]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.04586226583447821 

Finding optimal parameters using Gradient Descent
theta values :
[[17.32099327]
 [ 4.43660913]
 [ 3.67618043]
 [ 1.55515028]] 

*********************************************************************************

**********************************************************************************
Iteration =  888
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[22.09848936]
 [10.78604027]
 [18.25031665]
 [18.15593255]] 

error = y_predicted - y
[[-0.00151064]
 [ 0.38604027]
 [-0.04968335]
 [-0.34406745]] 

sq_error = error **2
[[2.28202713e-06]
 [1.49027092e-01]
 [2.46843574e-03]
 [1.18382410e-01]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.03373502750486097 

Finding optimal parameters using Gradient Descent
theta values :
[[17.32271776]
 [ 4.49883893]
 [ 3.72582969]
 [ 1.53491921]] 

**********************************************************************************
Iteration =  889
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[22.09852743]
 [10.7849777 ]
 [18.25050607]
 [18.15685984]] 

error = y_predicted - y
[[-0.00147257]
 [ 0.3849777 ]
 [-0.04949393]
 [-0.34314016]] 

sq_error = error **2
[[2.16845704e-06]
 [1.48207832e-01]
 [2.44964926e-03

 [-0.27502475]] 

sq_error = error **2
[[3.81285123e-07]
 [9.42738123e-02]
 [1.34228901e-03]
 [7.56386128e-02]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.021406886933825683 

Finding optimal parameters using Gradient Descent
theta values :
[[17.32400898]
 [ 4.57533304]
 [ 3.78609623]
 [ 1.50920419]] 

**********************************************************************************
Iteration =  972
Step 1: Calculate the y_prediction 

y_predicted = np.dot(X, theta)
[[22.10063319]
 [10.70619422]
 [18.26349186]
 [18.22571665]] 

error = y_predicted - y
[[ 0.00063319]
 [ 0.30619422]
 [-0.03650814]
 [-0.27428335]] 

sq_error = error **2
[[4.00928207e-07]
 [9.37548987e-02]
 [1.33284418e-03]
 [7.52313547e-02]] 

m =  4
cost = sq_error.sum() / (2*m)
cost =  0.021289937316646537 

Finding optimal parameters using Gradient Descent
theta values :
[[17.32401889]
 [ 4.57615366]
 [ 3.78673841]
 [ 1.5089235 ]] 

********************************************************************************

In [ ]:
import matplotlib.pyplot as plt

plt.plot(plot_iteartion,plot_loss)